module.exports = {
  config: {
    name: "pickupline",
    version: "4.5.0",
    author: "Siam Ahmed Saan",
    countDown: 2,
    role: 0,
    shortDescription: "Get 150+ Bangla/English pickuplines with emojis",
    longDescription: "Get random flirty lines with emojis.",
    category: "FUN & SOCIAL",
    guide: "{pn} bangla / {pn} english"
  },

  onStart: async function ({ api, event, args }) {
    const banglaLines = [
      "আপনি কি গুগল? কারণ আমার খুঁজে পাওয়া সব কিছু আপনার মধ্যে আছে। 😉🔍",
      "আমার ফোনে কিছু একটা সমস্যা হয়েছে, আপনার নম্বরটা নেই! 📱💖",
      "আপনি কি ম্যাপ? কারণ আমি আপনার চোখে হারিয়ে যাচ্ছি। 🗺️👀",
      "আপনার হাসিটা কি WiFi? কারণ আমি কানেকশন খুঁজে পাচ্ছি। 📶😍",
      "আমি কি আপনার ছবি তুলতে পারি? প্রমান দরকার যে পরিরাও পৃথিবীতে আছে। 📸🧚‍♀️",
      "আপনি কি কোনো ব্যাংক লোন? কারণ আপনার ওপর আমার ইন্টারেস্ট বেড়েই চলেছে। 💰📈",
      "আপনি কি কিবোর্ড? কারণ আপনি একদম আমার 'Type'! ⌨️❤️",
      "আমার হার্টটা চুরি হয়ে গেছে, আপনি কি চেক করবেন আপনার ব্যাগে আছে কি না? 🎒💘",
      "আপনি কি চা? কারণ আমার ক্লান্তি দূর করতে আপনিই যথেষ্ট। ☕✨",
      "আপনি কি জাদুকর? কারণ আপনার দিকে তাকালে বাকি সবাই ভ্যানিশ হয়ে যায়। 🪄✨",
      "আপনার চোখে কি নেশা আছে? তাকালেই মাথা ঘোরে। 😵‍💫👀",
      "আমার মনে হয় আমি হারিয়ে গেছি, আপনার মনের ঠিকানাটা পাওয়া যাবে? 📍❤️",
      "আপনার নামের পাশে কি আমার নামটা লেখা যায়? ✍️💞",
      "আপনি কি জান্নাত থেকে এসেছেন? কারণ আপনার সৌন্দর্য স্বর্গীয়। 😇✨",
      "পৃথিবীর সব ফুল একদিকে আর আপনার হাসি একদিকে। 🌹😊",
      "আপনি কি কোনো স্বপ্ন? কারণ আমি চাই না এই ঘুম ভাঙুক। 😴🌈",
      "আপনি কি ব্লুটুথ? কারণ আমি কানেক্ট হতে চাচ্ছি। 🦷🔗",
      "আপনার ওপর কি জরিমানা হওয়া উচিত? কারণ আপনি প্রতিদিন এতো সুন্দর কেন! ⚖️😘",
      "আপনি কি ট্রাফিক সিগন্যাল? আপনাকে দেখলে আমি থমকে যাই। 🚦🛑",
      "আপনার কি কোনো যমজ বোন আছে? না থাকলে আপনিই পৃথিবীর সেরা। 👯‍♀️🥇",
      "আমার ডায়েট চার্টে আপনার মিষ্টি হাসিটা কি যোগ করা যাবে? 🍎😋",
      "আপনি কি লাইব্রেরি কার্ড? কারণ আমি আপনাকে চেক আউট করতে চাই। 📚📑",
      "আপনি কি কফি? কারণ আপনি আমাকে জাগিয়ে রাখেন। ☕🔥",
      "আমার ফোনের চার্জ শেষ, আপনার নম্বরটা দিলে কল দিতাম। 🪫📞",
      "আপনি কি রোদ? কারণ আমার মেঘলা দিনে আপনাকে দরকার। ☀️☁️",
      "আপনার কাছে কি একটু সময় হবে? আমি একটা প্রেমপত্র লিখতে চাই। 💌⏳",
      "আপনি কি আর্কিটেক্ট? কারণ আপনি আমার মনের ঘর তৈরি করেছেন। 🏠🏗️",
      "আমার জিপিএস কাজ করছে না, আপনার বাড়ির রাস্তাটা কি বলবেন? 🧭🏠",
      "আপনি কি চকলেট? কারণ আপনি খুব সুইট। 🍫🍫",
      "আমি কি আপনার ছায়া হতে পারি? সব সময় পাশে থাকতাম। 👥💓",
      "আপনার হাসি কি সংক্রামক? কারণ আমি দেখলেই হাসতে শুরু করি। 😊🎉",
      "আমার অন্ধকার জীবনে আপনি এক টুকরো আলো। 💡🌟",
      "হাজার মানুষের ভিড়েও আমার চোখ শুধু আপনাকেই খোঁজে। 🫂🔎",
      "আমি হয়তো নিখুঁত নই, কিন্তু আপনার জন্য আমি সেরা হতে চাই। 💪❤️",
      "আপনার নীরবতাও আমার কাছে অনেক কথা বলে। 🤫💬",
      "কপাল ভালো থাকলে হয়তো একদিন আপনাকে সত্যি নিজের করে পাবো। 🍀💍",
      "আপনি আমার জীবনের সেই অপূর্ণ ইচ্ছা যা আমি পূর্ণ করতে চাই। 🌠💫",
      "আপনার চোখে তাকালে আমি নিজের অস্তিত্ব ভুলে যাই। 😵‍💫💖",
      "আমার পৃথিবীতে আপনিই একমাত্র রাজকন্যা। 👑👸",
      "সময় থমকে যাক যখন আমি আপনার পাশে থাকি। ⏳🛑",
      "আপনাকে অনুভব করতে কোনো কারণ লাগে না। ❤️🍃",
      "আপনি কি ধ্রুবতারা? কারণ আপনি আমাকে পথ দেখান। 🌟🧭",
      "আমার হৃদস্পন্দন আপনার নামে স্পন্দিত হয়। 💓💓",
      "আপনার সুখই আমার একমাত্র চাওয়া। 😊🤲",
      "আপনি আমার গল্পের প্রধান চরিত্র। 📖🎭",
      "আপনাকে হারানোর ভয়টা আমার সবচেয়ে বড় ভয়। 😰💔",
      "আপনার সাথে কাটানো প্রতিটা সেকেন্ড আমার কাছে মূল্যবান। ⏱️💎",
      "আমি চাই আমাদের শেষ নিঃশ্বাসটা যেন একসাথেই হয়। 🌬️💞",
      "আপনি কি সেই প্রার্থনা যা কবুল হয়েছে? 🤲✨",
      "আমার সবটুকু ভালোবাসা শুধু আপনার জন্য। ❤️🎁",
      "আপনি আমার জীবনের শ্রেষ্ঠ প্রাপ্তি। 🏆🌟",
      "আপনি কি কোনো পাসওয়ার্ড? কারণ আপনাকে ছাড়া আমার জীবন আনলক হয় না। 🔐🔓",
      "আপনার কি কোনো সুপারপাওয়ার আছে? আপনি সহজেই মন জয় করে ফেলেন। 🦸‍♀️💖",
      "আপনি কি কোনো দামি পারফিউম? আপনার রেশ রয়ে যায় সবখানে। 🧴🌸",
      "আপনি কি কোনো সিনেমা? কারণ আমি আপনাকে বারবার দেখতে চাই। 🎬🍿",
      "আপনার কথাগুলো কি কোনো গান? কানে বাজতেই থাকে। 🎶🎧",
      "আমি কি আপনার প্রোফাইলের মতো বাস্তবেও আপনাকে পছন্দ করতে পারি? 📱🤩",
      "আপনি কি কোনো নোটিফিকেশন? আপনাকে দেখলেই মন ভালো হয়ে যায়। 🔔🥰",
      "আপনার স্টাইলটা একদম কিলার! 🔪😎",
      "আপনি কি ইনসুলিন? কারণ আপনি খুব সুইট। 💉🍭",
      "আপনি কি কোনো পেইন্টিং? কারণ আপনি ফ্রেম করার মতো সুন্দর। 🖼️🎨",
      "আপনার হাসি কি এনার্জি ড্রিংক? দেখলেই এনার্জি পাই। ⚡🥤",
      "আপনি কি কোনো অ্যাপ? কারণ আমার লাইফে আপনাকে দরকার। 📲💎",
      "আপনার চোখ দুটো যেন গভীর কোনো সমুদ্র। 🌊👀",
      "আপনি কি কোনো কবিতা? যার প্রতিটি লাইন স্পেশাল। 📝🌻",
      "আপনি কি বৃষ্টির ফোঁটা? যা মনকে শান্ত করে। 🌧️😌",
      "আপনার সাথে পরিচয় হওয়াটা কি ভাগ্যের ব্যাপার? 🎰💖",
      "আপনি কি কোনো গয়না? যা সব সময় উজ্জ্বল থাকে। 💍✨",
      "আপনার কথা বলার স্টাইলটা দারুণ! 🗣️🔥",
      "আপনি কি কোনো বসন্তের বাতাস? 🍃🌸",
      "আমার একঘেয়ে জীবনে আপনি একটা টুইস্ট। 🎢🌀",
      "আপনাকে দেখলে মনে হয় অনেক দিনের চেনা। 🤝❤️",
      "আপনার হাসিতে কোনো জাদু আছে কি? 🪄😊",
      "আপনি কি তারা? কারণ আপনি অনেক দূর থেকেও উজ্জ্বল। 🌌⭐",
      "আমি কি আপনার হাতটা ধরতে পারি? 🤝💕",
      "আপনার সাহচর্য আমার খুব প্রিয়। 🤗✨",
      "আপনি কি ডায়েরি? আমার সব কথা আপনাকে বলতে চাই। 📖🖋️",
      "আপনাকে ছাড়া পৃথিবীটা ধূসর মনে হয়। 🌍🌑",
      "আপনি কি শরতের কাশফুল? এতো শুভ্র কেন! 🌾🤍",
      "আপনার মনের দরজায় কি নক করা যাবে? 🚪✊",
      "আমি কি আপনার সাথে এক কাপ কফি খেতে পারি? ☕💏",
      "আপনি কি আইসক্রিম? কারণ আপনাকে দেখলে মন গলে যায়। 🍦🫠",
      "আপনি কি পেন্সিল? কারণ আমি আপনার সাথে ফিউচার আঁকতে চাই। ✏️🖼️",
      "আপনার জন্য আমার মনে আলাদা একটা সফট কর্নার আছে। 🧸💗",
      "আপনি কি নীল আকাশ? যেখানে আমি ডানা মেলতে চাই। ☁️🕊️",
      "আপনার সাথে কথা বললে সব টেনশন ভুলে যাই। 💆‍♂️✨",
      "আপনি কি কোনো ধাঁধা? যা আমি সারাজীবন সমাধান করতে চাই। 🧩🤔",
      "আপনার সান্নিধ্য আমার শক্তি। 💪❤️",
      "আপনি কি কোনো উপন্যাসের নায়িকা? 👸📚",
      "আপনার সাথে কাটানো মুহূর্তগুলো ফ্রেমবন্দি করে রাখতে চাই। 🖼️📸",
      "শেষ কথা, আপনি কি আমার হবেন? 💍❓",
      "আপনার জন্য আমার হৃদয়ে একটা আলাদা ফোল্ডার আছে। 📂💓",
      "আপনি কি ম্যাজিক? আপনার ছোঁয়ায় সব বদলে যায়। 🪄🧚‍♂️",
      "আপনার এক পলক দেখা মানেই আমার দিনটা সার্থক। 🌅👌",
      "আপনি কি কোয়ান্টাম ফিজিক্স? বোঝা কঠিন কিন্তু খুব ইন্টারেস্টিং! ⚛️🧐",
      "আমি কি আপনার হৃদয়ে এক টুকরো জমি পেতে পারি? 🏡💓",
      "আপনি কি আমার সেই হারানো সুর? 🎵🎹",
      "আপনার সাথে কথা বলাটা আমার দিনের প্রিয় কাজ। 🗣️☀️",
      "আপনি কি ক্যানভাস? আমি আপনাকে ভালোবাসার রঙে রাঙাতে চাই। 🎨❤️",
      "আপনার জন্য আমার হৃদয়ে কি একটু জায়গা হবে? 💖🏠",
      "আপনি কি লটারি? কারণ আপনাকে পাওয়া ভাগ্যের ব্যাপার। 🎫🤩",
      "আপনার কন্ঠস্বর যেন শরতের মিষ্টি সকাল। 🌤️🎶",
      "আপনার গলার স্বর আমার খুব প্রিয়। 🎤🥰",
      "আমার ফোনের গ্যালারিতে আপনার জন্য স্পেস খালি আছে। 📸📂",
      "আপনি কি চাঁদের আলো? রাতের আঁধারে আমার পথ দেখান। 🌙🌟",
      "আপনার সাথে কথা বললে মনে হয় মেঘের ওপর ভাসছি। ☁️🥰",
      "আমি কি আপনার হাতটা সারা জীবনের জন্য ধরতে পারি? 🤝💍",
      "আপনি কি কোনো রাজকীয় ফুল? যার ঘ্রাণে আমি মুগ্ধ। 🌹👑",
      "আপনার হাসি দেখলে আমার সব দুঃখ উবে যায়। 😊✨",
      "আপনি কি আমার সেই না বলা কথা? 🤫💌",
      "আপনার প্রতি আমার টান যেন মহাকর্ষ বল। 🌍🧲",
      "আপনি কি কোনো মিউজিক ভিডিওর ক্রাশ? 🎬💘",
      "আমার প্রতিটি দোয়ায় আমি আপনাকে চাই। 🤲❤️",
      "আপনি কি জোনাকি? আমার অন্ধকার রাতের বন্ধু। 🪲💡",
      "আপনার চোখের ভাষা আমি পড়তে চাই। 👀📖",
      "আপনি কি বসন্তের প্রথম দিন? 🌸🍃",
      "আপনার সাথে এক কাপ চা আর অনেকটা সময় কাটাতে চাই। ☕⏳",
      "আপনি কি আমার জীবনের ধ্রুবক? যা কখনো বদলাবে না। 🔢🔒",
      "আপনার চাহনিতে কি মায়া মাখানো আছে? 😍✨",
      "আমি কি আপনার স্বপ্নের রাজপুত্র হতে পারি? 🤴🐎",
      "আপনার নামটা আমার পাসওয়ার্ড হতে পারে? 🔑💓",
      "আপনি কি রোদ্দুর? বরফ গলা ভালোবাসা দেবেন? ☀️🧊",
      "আপনার হাসির শব্দ আমার প্রিয় রিংটোন। 🎵😊",
      "আপনি কি কোনো গল্পের রাজকুমারী? 👸🏰",
      "আপনার সাথে পরিচয় হওয়াটাই আমার সেরা উপহার। 🎁❤️",
      "আপনি কি স্নিগ্ধ সকালের শিশির? 💧🌱",
      "আপনার জন্য আমি সারা রাত জেগে থাকতে পারি। 🌃👀",
      "আপনি কি কোনো দামী গিফট বক্স? 🎁💎",
      "আপনার মায়ার জালে আমি আটকে গেছি। 🕸️💓",
      "আপনি কি কৃষ্ণচূড়া? এতোটা লাল মায়া কেন! 🌺😍",
      "আপনার জন্য আমার মনে স্পেশাল একটা গান বাজে। 🎸🎶",
      "আপনি কি ফাগুনের আগুন? মনে ভালোবাসার রঙ লাগালেন। 🔥🎨",
      "আপনার সাথে বৃষ্টিতে ভিজতে চাই। 🌧️☔",
      "আপনি কি পাহাড়ের ঝর্ণা? এতোটা চঞ্চল কেন! 🏔️🌊",
      "আপনার চোখে তাকালে পুরো দুনিয়া ভুলে যাই। 🌍😵",
      "আপনি কি কোনো আর্ট গ্যালারির সেরা ছবি? 🖼️✨",
      "আপনার সাথে কাটানো সময়টা সব সময় শর্ট মনে হয়। ⌛🏃",
      "আপনি কি আমার জীবনের সেরা অধ্যায়? 📖💖",
      "আপনার মিষ্টি কথায় আমি দিওয়ানা। 🗣️🍭",
      "আপনি কি আকাশের রামধনু? 🌈✨",
      "আপনার জন্য আমি সাত সমুদ্র তেরো নদী পার হতে পারি। 🌊⛵",
      "আপনি কি হৃদয়ের স্পন্দন? যা ছাড়া আমি অচল। 💓💓",
      "আপনার স্পর্শে সব পাথরও যেন প্রাণ পায়। 💎✨",
      "আপনি কি আমার হারানো ছোটবেলা? 🧸🎈",
      "আপনার সাথে জীবনটা খুব রঙিন মনে হয়। 🎨❤️",
      "আপনি কি রাতের শেষ তারা? 🌌⭐",
      "আপনার মায়াবী হাসি আমার দিন বদলে দেয়। 😊🌟",
      "আমি কি আপনার পাশে বসে একটু নীরবতা কাটাতে পারি? 🤫🛋️",
      "আপনি কি আমার জীবনের সেরা ডিসিশন? ✅💖",
      "আপনার ভালোবাসা আমার জন্য এক সমুদ্র শান্তি। 🌊😌",
      "আপনি কি আমার চিরস্থায়ী ঠিকানা? 🏠💓",
      "১৫০ নম্বর পিকআপ লাইন: আপনার জন্য আমার ভালোবাসা অফুরন্ত। 💯♾️"
    ];

    const englishLines = [
      "Are you a keyboard? Because you're just my type. ⌨️💘",
      "Do you believe in love at first sight, or should I walk by again? 👀🚶‍♂️",
      "Is your name Google? Because you have everything I’m searching for. 🔍✨",
      "Are you a camera? Every time I look at you, I smile. 📸😊",
      "Are you French? Because Eiffel for you. 🗼🗼",
      "If you were a triangle, you'd be acute one. 📐😘",
      "I’m not a photographer, but I can definitely picture us together. 🖼️💞",
      "Do you have a map? I just got lost in your eyes. 🗺️😍",
      "Are you a Wi-Fi router? Because I'm feeling a connection. 📶🔥",
      "Is there an airport nearby or is it my heart taking off? 🛫💓",
      "If beauty were time, you’d be an eternity. ⏳♾️",
      "Are you a magician? Whenever I look at you, everyone else disappears. 🪄✨",
      "Do you have a Band-Aid? I scraped my knee falling for you. 🩹🩹",
      "Are you an interior decorator? Because when I saw you, the room became beautiful. 🏠✨",
      "If I could rearrange the alphabet, I’d put 'U' and 'I' together. 🔠❤️",
      "Are you a parking ticket? Because you’ve got 'FINE' written all over you. 🎫🔥",
      "Your hand looks heavy, can I hold it for you? 🤝💖",
      "I’m writing a phone book, can I have your number? 📖📞",
      "Are you a campfire? Because you're hot and I want s'more. 🔥🍢",
      "Is your name Wi-Fi? Because I'm really feeling a connection. 📶💘",
      "Are you a light bulb? Because you brighten up my day. 💡☀️",
      "Life without you is like a broken pencil, pointless. ✏️💔",
      "Are you a time traveler? Because I see you in my future. ⏳🚀",
      "Do you like Star Wars? Because Yoda only one for me! 🌌👽",
      "I’m lost. Can you give me directions to your heart? 🧭❤️",
      "Are you a fruit? Because you're a Fine-apple. 🍍😏",
      "Do you have a sunstroke, or are you always this hot? ☀️🔥",
      "Is your dad a baker? Because you're a cutie pie. 🥧🥧",
      "Can I follow you home? My parents told me to follow my dreams. 🚶‍♂️💭",
      "Are you a bank loan? Because you have my interest. 💰📈",
      "I’m not a genie, but I can make your dreams come true. 🧞‍♂️✨",
      "Are you a cat? Because I’m feline a connection. 🐱🐾",
      "Are you the sun? Because my world revolves around you. ☀️🌍",
      "Are you a volcano? Because I lava you. 🌋❤️",
      "Your eyes are like IKEA. I get lost in them. 🛒👀",
      "Are you a 45-degree angle? Because you’re acute-y. 📐😜",
      "Are you a snowflake? Because I’ve fallen for you. ❄️❄️",
      "I must be a snowflake, because I've fallen for you. ❄️💖",
      "Are you a dictionary? Because you add meaning to my life. 📖✨",
      "Are you a charger? Because I’m dying without you. 🔌🪫",
      "Are you a password? Because you're hard to forget. 🔐🧠",
      "Is your heart a prison? I want to be sentenced to life. ⛓️❤️",
      "Are you a trophy? Because I want to win you. 🏆🥇",
      "Are you a diamond? Because you are rare and precious. 💎💎",
      "Are you a magnet? Because I'm attracted to you. 🧲🧲",
      "Are you a star? Because you shine so bright. ⭐✨",
      "Are you an angel? Because heaven is missing one. 😇☁️",
      "Are you a mirror? Because I see my future in you. 🪞💖",
      "Are you a rose? Because you are beautiful. 🌹🥀",
      "Are you gravity? Because you keep me grounded. 🌍⚓",
      "Are you a puzzle? Because I want to piece us together. 🧩💞",
      "Are you a song? Because I want to play you on repeat. 🎶🔁",
      "Are you a key? Because you unlocked my heart. 🔑🔓",
      "Are you a breath of fresh air? You take my breath away. 🌬️😌",
      "Are you a match? Because we are a perfect pair. 🕯️🔥",
      "Are you a compass? Because you lead me home. 🧭🏠",
      "Are you an anchor? Because you hold me down. ⚓❤️",
      "Are you a flame? Because you're lighting up my soul. 🔥🕯️",
      "Are you an ocean? Because I’m drowning in you. 🌊🏊‍♂️",
      "Are you a comet? Because you're one in a million. ☄️🌟",
      "Are you a treasure? Because I’ve been hunting for you. 🏴‍☠️💎",
      "Are you a rainbow? Because you bring color to my life. 🌈🎨",
      "Are you a painting? Because you're a masterpiece. 🖼️👩‍🎨",
      "Are you a melody? Because you're stuck in my head. 🎵🧠",
      "Are you a dream? Because I don't want to wake up. 😴✨",
      "Are you a miracle? Because you're too good to be true. ✨🙏",
      "Are you a story? I want to read every page of you. 📖📖",
      "Are you a wish? Because you just came true. 🌠💖",
      "Are you a gift? Because I'm so lucky to have you. 🎁🍀",
      "Are you a sunset? Because you're breathtaking. 🌅😍",
      "Are you a moon? Because you light up my darkest nights. 🌙🌑",
      "Are you a firefly? Because you make my heart glow. 🪲💡",
      "Are you a butterfly? Because you give me butterflies. 🦋🦋",
      "Are you a diamond? Because you're forever. 💎♾️",
      "Are you a whisper? Because you're all I hear. 🗣️👂",
      "Are you a spark? Because you started a fire in me. ✨🔥",
      "Are you a poem? Because you're beautiful and deep. 📝💘",
      "Are you a symphony? Because you're harmonious. 🎻🎶",
      "Are you a galaxy? Because you're vast and beautiful. 🌌🤩",
      "Are you a lighthouse? Because you guide me. 🏮🌊",
      "Are you a candle? Because you consume me. 🕯️🔥",
      "Are you a season? You are my favorite time of year. 🍂🌸",
      "Are you a rhythm? Because my heart beats to your tune. 🥁💓",
      "Are you a jewel? Because you're priceless. 💎💎",
      "Are you a queen? Because you rule my heart. 👑👸",
      "Are you a hero? Because you saved me from boredom. 🦸‍♂️💥",
      "Are you a pilot? Because you take my heart higher. ✈️☁️",
      "Are you a captain? Because you're steering my life. 🚢⚓",
      "Are you a traveler? You've been running through my mind. 🏃‍♂️🧠",
      "Are you a soldier? Because you've conquered my heart. 🎖️❤️",
      "Are you a doctor? Because you just healed my heart. 👨‍⚕️💖",
      "Are you a teacher? Because you taught me how to love. 🍎📚",
      "Are you an artist? You painted a smile on my face. 🎨😊",
      "Are you a gardener? Because you made my heart bloom. 🌻🌻",
      "Are you a scientist? Because we have great chemistry. 🧪🔬",
      "Are you a chef? You're cooking up some feelings. 👨‍🍳🔥",
      "Are you a thief? Because you just stole my heart. 🥷❤️",
      "Are you a battery? Because you give me energy. 🔋⚡",
      "Are you a cloud? Because you're so dreamy. ☁️💤",
      "Are you a compass? Because you guide me to love. 🧭💞",
      "Are you a lock? Because I'm the key to your heart. 🔒🔑",
      "Are you a candle? My light in the dark. 🕯️🌑",
      "Are you an alien? Because you're out of this world. 👽🌌",
      "Are you a volcano? Erupting with beauty. 🌋✨",
      "Are you a book? I want to study every page. 📖🧐",
      "Are you a bridge? You connect me to happiness. 🌉😊",
      "Are you a star? The brightest in my sky. ⭐🌌",
      "Are you a wish? Everything I wanted. 🌠💖",
      "Are you a mirror? I see perfection in you. 🪞👌",
      "Are you a ghost? Always haunting my dreams. 👻💤",
      "Are you a heartbeat? You keep me going. 💓⚡",
      "Are you a peace? Because you're my quiet place. 🕊️😌",
      "Are you a soulmate? We're perfect together. 👫💍",
      "Are you a destiny? I was meant to find you. 🎡💫",
      "Are you a future? I want to spend it with you. ⏳💗",
      "Are you a miracle? You are a blessing to me. ✨🙏",
      "Are you a secret? I want to keep you forever. 🤫🔒",
      "Are you a home? I'm comfortable with you. 🏠😌",
      "Are you a life? Because you're my everything. 🌍💖",
      "Are you a heartbeat? You keep me alive. 💓⚡",
      "Are you the one? Because I know you are. ☝️💍",
      "Are you my favorite notification? 🔔🥰",
      "Are you a lucky charm? You bring me luck. 🍀✨",
      "Are you an oasis? Because you're my paradise. 🏝️🌊",
      "Are you a pearl? You are rare and beautiful. 🐚💎",
      "Are you a diamond? Because you're forever. 💎💍",
      "Are you a dream? You're too good to be true. 💤✨",
      "Are you my sunlight? You warm my soul. ☀️🔥",
      "Are you a poem? You are perfect. 📝💖",
      "Are you a melody? My heart dances to you. 🎶💃",
      "Are you a star? My guiding light. ⭐🧭",
      "Are you my happiness? You're all I need. 😊💗",
      "Are you the last line? Because you're the one. 💯💍"
    ];

    const input = args[0]?.toLowerCase();

    if (input === "bangla") {
      const line = banglaLines[Math.floor(Math.random() * banglaLines.length)];
      return api.sendMessage(`✨ [Bangla Pickupline] ✨\n\n${line}`, event.threadID, event.messageID);
    } 
    
    if (input === "english") {
      const line = englishLines[Math.floor(Math.random() * englishLines.length)];
      return api.sendMessage(`💖 [English Pickupline] 💖\n\n${line}`, event.threadID, event.messageID);
    }

    return api.sendMessage("⚠️ Please use:\n/pickupline bangla\nOR\n/pickupline english", event.threadID, event.messageID);
  }
};
